version: 5.1.{build}
install:
- ps: "Set-AppveyorBuildVariable 'APPVEYOR_BUILD_INFO_VERSION' $env:APPVEYOR_BUILD_VERSION"
- ps: "if ($env:APPVEYOR_REPO_BRANCH -ieq \"development\")\n{\n Set-AppveyorBuildVariable 'APPVEYOR_BUILD_INFO_VERSION' $($env:APPVEYOR_BUILD_INFO_VERSION + '-beta') \n}"
branches:
  only:
  - master
  - development  
skip_tags: true
configuration: Release
image: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(APPVEYOR_BUILD_INFO_VERSION)'
#cache: src\packages
nuget:
  project_feed: true
  disable_publish_on_pr: true
before_build:
  - nuget restore -DisableParallelProcessing
build_script:
- cmd: msbuild SelfishHttp.sln /t:rebuild /tv:14.0 /p:Configuration=Release;TargetFrameworkVersion=v4.6
after_build:
- cmd: msbuild SelfishHttp/SelfishHttp.csproj /t:rebuild /tv:14.0 /p:Configuration=Release;TargetFrameworkVersion=v4.6;DefineConstants=SKIP_POST_BUILD
- cmd: msbuild SelfishHttp/SelfishHttp.csproj /t:rebuild /tv:14.0 /p:Configuration=Release;TargetFrameworkVersion=v4.5;DefineConstants=SKIP_POST_BUILD
- cmd: msbuild SelfishHttp/SelfishHttp.csproj /t:rebuild /tv:14.0 /p:Configuration=Release;TargetFrameworkVersion=v4.0;DefineConstants=SKIP_POST_BUILD
- ps: ".\\Tools\\NuGet.exe pack .\\SelfishHttp.nuspec -BasePath .\\ -OutputDirectory .\\ -Exclude *.dll -Version $env:APPVEYOR_BUILD_INFO_VERSION -Verbosity detailed"
#test_script:
#- vstest.console /logger:Appveyor /TestAdapterPath:"%APPVEYOR_BUILD_FOLDER%\src\packages\Fixie.1.0.0.3\lib\net45" "%APPVEYOR_BUILD_FOLDER%\src\Portable.MediatR.Tests\bin\Release\Portable.MediatR.Tests.dll"
test: off
artifacts:
- path: \**\*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: YPGdPLnY9FEYDZz3zZFV/+BKreynP4W2/DoURr0XlBjS8eLkkSypvEkI0BQSfRur
  artifact: /.*\.nupkg/
  on:
    branch: /master|Development/